[providers]
python = "3.11"

[build]
buildCommand = "pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt"

[start]
cmd = "cd backend && gunicorn -w 4 -b 0.0.0.0:$PORT app:app"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"